#!/usr/bin/env python
import os
import mysql.connector
from mysql.connector import errorcode
import yaml

host="@host"
port=@port
dbname="@dbname"
user="@user"
password="@password"

try:
  connection =  mysql.connector.connect(host=host,
                                user=user,
                                port=port,
                                password=password,
                                database=dbname)
  print(" Connection established to the database [{}]".format(dbname))
except mysql.connector.Error as err:
  if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
    print("Something is wrong with your user name or password")
    pass
  elif err.errno == errorcode.ER_BAD_DB_ERROR:
    print("Database does not exist")
    pass
  else:
    print(err)
    pass



tablename="@tablename"
colname="@colname"
val=None
id_col="@id_col"
struc_id="@struc_id"


with open("objective.yml", "r") as fr:
    objective = yaml.safe_load(fr)

val = objective["@colname"]



def insert_value(tablename, colname, val, id_col, struc_id, dbcon=connection):
    try:
        self.cursor = dbcon.cursor()
        sql = f"UPDATE   {tablename} SET  {colname}= {val} WHERE {id_col}='{struc_id}'"
        self.cursor.execute(sql)
    except Exception as ex:
        print(f"{ex}")
    finally:
        self.cursor.close()




